- block:

  - redhat_subscription:
      state: present
      username: "{{ rhid }}"
      password: "{{ rhpass }}"
      pool_ids: "{{ rhPoolID }}"
    poll: 30
    async: 300
    tags: rh_subscription

  - name: Enable all repositories starting with RHEL7
    rhsm_repository:
      name: "{{ rhsm_repo_7 }}"
      state: enabled
      purge: true
    when:
    - ansible_distribution_major_version == '7'
    poll: 30
    async: 300
    tags: rh_repos


  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    poll: 30
    async: 600
    tags: yum_update

  - name: Install a list of packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ yum_list }}"
    poll: 30
    async: 300
    ignore_errors: yes
    register: yum_stat
    tags: yum_install


- name: "({{ ROLE_ID }} - 001.01) Copy vsftpd configure template file"
  template:
      src: vsftpd.conf.j2
      dest: /etc/vsftpd/vsftpd.conf
      owner: root
      group: root
      mode: '0600'
      backup: yes

- name: "({{ ROLE_ID }} - 001.02) Create chroot_list file"
  file:
    path: /etc/vsftpd/chroot_list
    state: touch

